<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { state, go, money, today, dateLabel, business, service, availableSlots, bookingTotal, createBooking, updateBooking } from '../core/state'
import AppIcon from '../components/AppIcon.vue'
import AppModal from '../components/AppModal.vue'
const draft=reactive({...{businessId:state.selectedBusinessId,serviceId:'',staffId:'',resourceId:'',date:today(),time:'',partySize:1,coupon:'',paymentMethod:'onsite',notes:''},...(state.bookingDraft||{})})
const step=ref(draft.resumeStep||1)
const error=ref('')
const couponError=ref('')
const appliedCoupon=ref(draft.appliedCoupon||draft.coupon||'')
const paymentOpen=ref(false)
const paymentMethod=ref('mpesa')
const paymentState=ref('ready')
const created=ref(null)
const current=computed(()=>business(draft.businessId))
const selectedService=computed(()=>service(draft.serviceId))
const options=computed(()=>state.db.services.filter(s=>s.businessId===draft.businessId&&s.active))
const people=computed(()=>state.db.staff.filter(p=>p.active&&p.businessId===draft.businessId&&p.serviceIds.includes(draft.serviceId)))
const resources=computed(()=>state.db.resources.filter(r=>r.active&&r.businessId===draft.businessId&&r.type===selectedService.value?.resourceType&&Number(r.capacity)>=Number(draft.partySize)))
const isRestaurant=computed(()=>current.value?.category==='Restauração')
const slots=computed(()=>availableSlots({...draft,excludeBookingId:draft.excludeBookingId}))
const totals=computed(()=>{
  const original=state.db.bookings.find(b=>b.id===draft.excludeBookingId)
  if(original && original.serviceId===draft.serviceId && Number(original.partySize||1)===Number(draft.partySize||1) && (original.coupon||'')===appliedCoupon.value) return {total:original.total,subtotal:original.subtotal,discount:original.discount||0,coupon:original.coupon}
  return bookingTotal({serviceId:draft.serviceId,coupon:appliedCoupon.value,partySize:draft.partySize,businessId:draft.businessId})
})
const dates=computed(()=>Array.from({length:7},(_,index)=>{const date=new Date(`${today()}T12:00:00`);date.setDate(date.getDate()+index);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}))
const maxDate=computed(()=>{const date=new Date(`${today()}T12:00:00`);date.setDate(date.getDate()+Number(state.db.settings.advanceDays||60));return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`})
const totalLabel=computed(()=>totals.value.error?money(selectedService.value?.price||0):money(totals.value.total))
watch(draft,()=>{state.bookingDraft={...draft,resumeStep:step.value,appliedCoupon:appliedCoupon.value}}, {deep:true,immediate:true})
watch(step,()=>{state.bookingDraft={...draft,resumeStep:step.value,appliedCoupon:appliedCoupon.value};error.value='';window.scrollTo({top:0,behavior:'smooth'})})
watch(()=>[draft.staffId,draft.resourceId,draft.date,draft.partySize],()=>{draft.time='';error.value=''})
function changeService() {draft.staffId='';draft.resourceId='';draft.time='';appliedCoupon.value='';draft.coupon=''}
function applyCoupon() {const price=bookingTotal({serviceId:draft.serviceId,coupon:draft.coupon,partySize:draft.partySize,businessId:draft.businessId});couponError.value=price.error||'';appliedCoupon.value=price.error?'':draft.coupon;state.bookingDraft={...draft,resumeStep:step.value,appliedCoupon:appliedCoupon.value}}
function next() {if(step.value===1&&!draft.serviceId){error.value='Escolha um serviço.';return}if(step.value===2&&!draft.time){error.value='Escolha um horário disponível.';return}step.value++}
function confirm() {
  error.value=''
  if(state.role==='guest'){state.returnView='booking';state.bookingDraft={...draft,resumeStep:3,appliedCoupon:appliedCoupon.value};go('auth');return}
  if(!availableSlots({...draft,excludeBookingId:draft.excludeBookingId}).includes(draft.time)){error.value='Este horário já não está disponível. Escolha outro horário.';step.value=2;return}
  if(draft.paymentMethod==='online' && !draft.excludeBookingId){paymentState.value='ready';paymentOpen.value=true;return}
  finish(draft.paymentStatus||'pending')
}
function finish(paymentStatus) {
  const user=state.db.users.find(u=>u.id===state.userId)
  const payload={...draft,coupon:appliedCoupon.value,paymentStatus,clientId:draft.clientId||state.userId,clientName:draft.clientName||user?.name||'Cliente',status:'confirmed'}
  const result=draft.excludeBookingId?updateBooking(draft.excludeBookingId,payload):createBooking(payload)
  if(!result.ok){error.value=result.error;paymentOpen.value=false;return}
  created.value=result.record;paymentOpen.value=false;step.value=4;state.bookingDraft=null
}
function downloadCalendar() {if(!created.value)return;const item=created.value;const start=new Date(`${item.date}T${item.time}:00`);const end=new Date(start.getTime()+item.duration*60000);const stamp=d=>d.toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';const escape=text=>String(text).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,m=>'\\'+m);const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Elo//PT','BEGIN:VEVENT',`UID:${item.id}@elo.local`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,`SUMMARY:${escape(selectedService.value.name)}`,`LOCATION:${escape(current.value.name+', '+current.value.address)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download=`${item.id}.ics`;a.click();URL.revokeObjectURL(url)}
</script>
<template>
  <div v-if="current" class="booking-workspace"><button v-if="step<4" class="text-button back-button" @click="step>1?step--:go('business')"><AppIcon name="arrow-left" :size="17"/>Voltar</button><header class="page-header"><div><span class="eyebrow">{{current.name}}</span><h1>{{step===4?'Tem um encontro marcado.':draft.excludeBookingId?'Um novo momento para si.':'Reserve um momento para si.'}}</h1><p>{{step===4?'Encontre todos os detalhes na sua área pessoal.':'Cada detalhe, à sua medida.'}}</p></div></header>
    <div v-if="step<4" class="booking-progress" aria-label="Progresso da marcação"><div v-for="(label,index) in ['Serviço e preferência','Data e horário','Confirmação']" :key="label" :class="{active:step===index+1,complete:step>index+1}"><span><AppIcon v-if="step>index+1" name="check" :size="15"/><template v-else>{{index+1}}</template></span><strong>{{label}}</strong></div></div>
    <div v-if="step<4" class="booking-layout"><section class="booking-form-section">
      <template v-if="step===1"><h2>Como podemos cuidar de si?</h2><label class="field">Serviço<select v-model="draft.serviceId" @change="changeService"><option value="" disabled>Seleccione um serviço</option><option v-for="item in options" :key="item.id" :value="item.id">{{item.name}} · {{money(item.price)}} · {{item.duration}} min</option></select></label><p v-if="selectedService" class="muted">{{selectedService.description}}</p><label v-if="isRestaurant" class="field">Número de pessoas<input type="number" v-model.number="draft.partySize" min="1" max="30"/></label><template v-if="people.length"><h3>Com quem prefere?</h3><div class="staff-options"><button :class="['staff-option',{selected:!draft.staffId}]" @click="draft.staffId=''"><span class="avatar"><AppIcon name="users"/></span><span><strong>Sem preferência</strong><small>Primeiro profissional disponível</small></span><AppIcon :name="!draft.staffId?'circle-check':'plus'" :size="18"/></button><button v-for="person in people" :key="person.id" :class="['staff-option',{selected:draft.staffId===person.id}]" @click="draft.staffId=person.id"><span class="avatar">{{person.name.split(' ').map(n=>n[0]).slice(0,2).join('')}}</span><span><strong>{{person.name}}</strong><small>{{person.title}}</small></span><AppIcon v-if="draft.staffId===person.id" name="circle-check" :size="18"/></button></div></template><label v-if="selectedService?.resourceType" class="field">{{isRestaurant?'Mesa':'Sala ou recurso'}}<select v-model="draft.resourceId"><option value="">Atribuição automática</option><option v-for="resource in resources" :key="resource.id" :value="resource.id">{{resource.name}} · {{resource.capacity}} {{resource.capacity===1?'lugar':'lugares'}}</option></select></label></template>
      <template v-if="step===2"><div class="section-heading"><h2>Qual é o melhor dia?</h2><label class="date-picker-label"><input type="date" v-model="draft.date" :min="today()" :max="maxDate" aria-label="Data da marcação"/></label></div><div class="booking-date-grid"><button v-for="date in dates" :key="date" :class="{selected:draft.date===date}" @click="draft.date=date"><small>{{new Intl.DateTimeFormat('pt-MZ',{weekday:'short'}).format(new Date(date+'T12:00:00'))}}</small><strong>{{date.slice(8)}}</strong><span>{{new Intl.DateTimeFormat('pt-MZ',{month:'short'}).format(new Date(date+'T12:00:00'))}}</span></button></div><div class="section-heading"><h3>Horários disponíveis</h3><span class="muted">{{selectedService?.duration}} minutos</span></div><div class="time-slot-grid"><button v-for="time in slots" :key="time" :class="{selected:draft.time===time}" @click="draft.time=time">{{time}}</button></div><div v-if="!slots.length" class="empty-state"><AppIcon name="calendar-clock" :size="32"/><h3>Sem horários neste dia</h3><p>Escolha outra data ou ajuste a preferência de profissional ou recurso.</p></div></template>
      <template v-if="step===3"><h2>Está quase tudo pronto.</h2><div class="review-details"><div><span>Estabelecimento</span><strong>{{current.name}}</strong></div><div><span>Serviço</span><strong>{{selectedService?.name}}</strong></div><div><span>Data e hora</span><strong>{{dateLabel(draft.date)}} · {{draft.time}}</strong></div><div><span>{{isRestaurant?'Pessoas':'Profissional'}}</span><strong>{{isRestaurant?draft.partySize:state.db.staff.find(p=>p.id===draft.staffId)?.name||'Primeiro disponível'}}</strong></div></div><label class="field">Pedido especial <span class="muted">(opcional)</span><textarea v-model="draft.notes" rows="2" placeholder="Algo que o estabelecimento deva saber?" maxlength="500"/></label><label class="field">Cupão de desconto<div class="inline-input"><input v-model.trim="draft.coupon" placeholder="O seu código"/><button class="btn secondary" type="button" @click="applyCoupon">Aplicar</button></div></label><p v-if="couponError" class="error-message">{{couponError}}</p><p v-else-if="appliedCoupon" class="success-message">Cupão {{appliedCoupon}} aplicado: menos {{money(totals.discount)}}.</p><h3>Como prefere pagar?</h3><label class="payment-choice" :class="{selected:draft.paymentMethod==='onsite'}"><input type="radio" v-model="draft.paymentMethod" value="onsite"/><AppIcon name="wallet"/><span><strong>No estabelecimento</strong><small>Pague no momento do atendimento.</small></span></label><label v-if="current.onlinePayment&&state.db.settings.onlinePayments&&!draft.excludeBookingId" class="payment-choice" :class="{selected:draft.paymentMethod==='online'}"><input type="radio" v-model="draft.paymentMethod" value="online"/><AppIcon name="credit-card"/><span><strong>Online</strong><small>M-Pesa, cartão ou referência. Pagamento de teste.</small></span></label><p class="policy-note"><AppIcon name="calendar-clock" :size="16"/>Pode cancelar ou reagendar até {{current.cancelHours}} horas antes.</p></template>
      <p v-if="error" class="error-message" role="alert">{{error}}</p><div class="form-actions"><span class="muted">Passo {{step}} de 3</span><button v-if="step<3" class="btn primary" :disabled="step===1?!draft.serviceId:!draft.time" @click="next">Continuar<AppIcon name="arrow-right" :size="17"/></button><button v-else class="btn primary" @click="confirm">{{state.role==='guest'?'Entrar para confirmar':draft.excludeBookingId?'Confirmar alteração':'Confirmar marcação'}}<AppIcon name="check" :size="17"/></button></div>
    </section><aside class="booking-summary"><img :src="current.image" :alt="current.name"/><div class="booking-summary-body"><span class="eyebrow">A SUA MARCAÇÃO</span><h3>{{current.name}}</h3><p><AppIcon name="map-pin" :size="14"/>{{current.city}}</p><div v-if="selectedService" class="summary-service"><strong>{{selectedService.name}}</strong><span><AppIcon name="clock" :size="15"/>{{selectedService.duration}} min</span></div><div v-if="draft.time" class="summary-service"><strong>{{dateLabel(draft.date)}}</strong><span>{{draft.time}}</span></div><div v-if="appliedCoupon&&!totals.error" class="summary-service"><span>Desconto</span><strong>−{{money(totals.discount)}}</strong></div><div class="summary-total"><span>Total</span><strong>{{totalLabel}}</strong></div></div><p class="summary-footnote"><AppIcon name="shield-check" :size="16"/>Os seus planos, bem organizados.</p></aside></div>
    <section v-else class="booking-confirmed"><span class="confirmation-icon"><AppIcon name="calendar-check" :size="40"/></span><span class="badge success">{{draft.excludeBookingId?'Marcação actualizada':'Marcação confirmada'}}</span><h2>{{selectedService?.name}}</h2><p>{{current.name}}</p><div class="confirmation-info"><span><AppIcon name="calendar-days"/>{{dateLabel(created?.date||draft.date)}}</span><span><AppIcon name="clock"/>{{created?.time||draft.time}}</span><span><AppIcon name="receipt"/>{{created?.id}}</span></div><p class="muted">{{created?.paymentStatus==='paid'?'Pagamento de teste aprovado.':created?.paymentMethod==='online'?'Pagamento online pendente.':'Pagamento no estabelecimento.'}} Total: {{money(created?.total||0)}}</p><div class="form-actions"><button class="btn secondary" @click="downloadCalendar"><AppIcon name="download" :size="17"/>Adicionar ao calendário</button><button class="btn primary" @click="go('appointments')">Ver marcações<AppIcon name="arrow-right" :size="17"/></button></div></section>
    <AppModal v-model="paymentOpen" title="Pagamento de teste"><div class="gateway-summary"><AppIcon name="credit-card" :size="30"/><span>Total a pagar<strong>{{totalLabel}}</strong></span></div><p class="local-note">Simulação local. Nenhum valor será cobrado e não são necessários dados bancários.</p><label class="field">Método<select v-model="paymentMethod"><option value="mpesa">M-Pesa</option><option value="card">Cartão</option><option value="reference">Referência</option></select></label><p v-if="paymentState==='declined'" class="error-message" role="alert">Pagamento recusado. Pode tentar novamente ou pagar no estabelecimento.</p><div class="gateway-actions"><button class="btn primary" @click="finish('paid')"><AppIcon name="check" :size="17"/>Aprovar pagamento de teste</button><button class="btn secondary" @click="finish('pending')">Manter pagamento pendente</button><button class="btn secondary" @click="paymentState='declined'">Testar recusa</button><button class="text-button" @click="paymentOpen=false;draft.paymentMethod='onsite'">Pagar no estabelecimento</button></div></AppModal>
  </div>
</template>
