<template>
  <main class="dashboard-page">
    <section class="dashboard-welcome"><div class="shell"><span class="eyebrow light">Área do cliente</span><h1>Olá, {{ firstName }}.</h1><p>Veja as próximas marcações, histórico e acções rápidas.</p></div></section>
    <div class="shell dashboard-shell">
      <div class="quick-actions client-actions"><button @click="go('explore')"><span>＋</span><strong>Nova marcação</strong><small>Pesquisar serviços</small></button><button @click="go('notifications')"><span>◉</span><strong>Notificações</strong><small>{{ unread }} por ler</small></button><button @click="go('profile')"><span>◎</span><strong>Perfil</strong><small>Dados da conta</small></button></div>
      <section class="dashboard-section"><div class="section-heading split compact-heading"><div><span class="eyebrow">Próximas</span><h2>Marcações activas</h2></div><button class="text-link" @click="go('explore')">+ Marcar</button></div><div v-if="upcoming.length" class="booking-cards"><article v-for="booking in upcoming" :key="booking.id" class="booking-card"><div class="booking-date"><small>{{ booking.date.split(' ')[1] }}</small><strong>{{ booking.date.split(' ')[0] }}</strong><span>{{ booking.time }}</span></div><div class="booking-info"><div class="booking-top"><StatusBadge :status="booking.status" /><small>{{ booking.id }}</small></div><h3>{{ service(booking.serviceId)?.name }}</h3><p>{{ salon(booking.salonId)?.name }} · {{ professional(booking.professionalId)?.name || 'Qualquer profissional' }}</p><div class="booking-meta"><span>{{ booking.payment }}</span><strong>{{ money(booking.total) }}</strong></div><div class="card-actions"><button class="btn btn-outline compact" @click="reschedule(booking)">Reagendar</button><button class="btn btn-ghost compact danger-text" @click="cancel(booking)">Cancelar</button></div></div></article></div><div v-else class="empty-state"><span>▣</span><h3>Sem marcações activas</h3><p>Pesquise um serviço e escolha um horário.</p><button class="btn btn-primary" @click="go('explore')">Explorar serviços</button></div></section>
      <section class="dashboard-section"><div class="section-heading compact-heading"><span class="eyebrow">Histórico</span><h2>Atendimentos anteriores</h2></div><div class="data-list"><div v-for="booking in history" :key="booking.id" class="data-row"><span class="service-icon small">{{ service(booking.serviceId)?.icon }}</span><div class="data-main"><strong>{{ service(booking.serviceId)?.name }}</strong><small>{{ salon(booking.salonId)?.name }} · {{ booking.date }}, {{ booking.time }}</small></div><StatusBadge :status="booking.status" /><strong class="desktop-only">{{ money(booking.total) }}</strong></div></div></section>
    </div>
    <ModalSheet><div v-if="store.modal==='cancel-booking'"><div class="sheet-head"><div><span class="eyebrow">Cancelar marcação</span><h2>Confirmar cancelamento?</h2></div><button class="icon-button" @click="closeModal">×</button></div><p class="muted">A acção é simulada e deve respeitar as políticas definidas pelo salão.</p><div class="warning-box">{{ service(store.modalPayload?.serviceId)?.name }} · {{ store.modalPayload?.date }} às {{ store.modalPayload?.time }}</div><div class="sheet-actions"><button class="btn btn-outline" @click="closeModal">Manter marcação</button><button class="btn btn-danger" @click="confirmCancel">Cancelar marcação</button></div></div></ModalSheet>
  </main>
</template>
<script>
import { appStore as store, go, helpers, openModal, closeModal, showToast, startBooking } from '../store'
import StatusBadge from '../components/StatusBadge.vue'
import ModalSheet from '../components/ModalSheet.vue'
export default { name:'ClientDashboard', components:{StatusBadge,ModalSheet}, data:()=>({store}), computed:{ firstName(){return store.user.name.split(' ')[0]}, unread(){return store.notifications.filter(n=>!n.read).length}, upcoming(){return store.bookings.filter(b=>b.status==='Confirmada')}, history(){return store.bookings.filter(b=>b.status!=='Confirmada')} }, methods:{ go,closeModal, salon:helpers.salonById,service:helpers.serviceById,professional:helpers.professionalById,money(v){return `${new Intl.NumberFormat('pt-MZ').format(v)} MT`}, cancel(b){openModal('cancel-booking',b)}, confirmCancel(){const b=store.modalPayload;if(b)b.status='Cancelada';closeModal();showToast('Marcação cancelada no mockup.')}, reschedule(b){startBooking(b.salonId,b.serviceId);store.booking.professionalId=b.professionalId;showToast('Escolha uma nova data e horário.')} } }
</script>
