<template>
  <main class="dashboard-page">
    <section class="dashboard-welcome professional-welcome"><div class="shell"><span class="eyebrow light">Área do profissional</span><h1>{{ title }}</h1><p>{{ subtitle }}</p></div></section>
    <div class="shell dashboard-shell">
      <div class="desktop-subnav desktop-only"><button :class="{active:store.view==='professional-dashboard'}" @click="go('professional-dashboard')">Agenda</button><button :class="{active:store.view==='professional-services'}" @click="go('professional-services')">Serviços autorizados</button><button :class="{active:store.view==='professional-availability'}" @click="go('professional-availability')">Disponibilidade</button><button :class="{active:store.view==='professional-history'}" @click="go('professional-history')">Histórico</button></div>

      <template v-if="store.view==='professional-dashboard'">
        <div class="metric-grid"><article><small>Hoje</small><strong>5</strong><span>atendimentos</span></article><article><small>Próximo</small><strong>08:00</strong><span>Sara M.</span></article><article><small>Concluídos</small><strong>{{ completed }}</strong><span>de 5</span></article></div>
        <section class="dashboard-section"><div class="section-heading split compact-heading"><div><span class="eyebrow">Agenda pessoal</span><h2>Hoje · 15 Setembro</h2></div><button class="btn btn-outline compact" @click="go('professional-availability')">Ajustar horário</button></div><div class="timeline-list"><article v-for="item in agenda" :key="item.id" class="timeline-item"><div class="timeline-time">{{ item.time }}</div><div class="timeline-card"><div class="timeline-main"><StatusBadge :status="item.status"/><h3>{{ item.client }}</h3><p>{{ item.service }}</p></div><div class="timeline-actions"><button class="btn btn-outline compact" v-if="item.status!=='Concluída'" @click="checkIn(item)">Confirmar presença</button><button class="btn btn-primary compact" v-if="item.status==='Em atendimento'" @click="complete(item)">Concluir</button></div></div></article></div></section>
      </template>

      <template v-else-if="store.view==='professional-services'">
        <section class="dashboard-section"><div class="section-heading compact-heading"><span class="eyebrow">Competências</span><h2>Serviços autorizados</h2><p>O profissional consulta os serviços que pode executar; a associação é gerida pelo administrador do salão.</p></div><div class="service-list"><article v-for="service in authorizedServices" :key="service.id" class="service-row"><span class="service-icon">{{ service.icon }}</span><div class="service-copy"><strong>{{ service.name }}</strong><small>{{ service.description }}</small><span>{{ service.duration }} min</span></div><StatusBadge status="Autorizado"/></article></div></section>
      </template>

      <template v-else-if="store.view==='professional-availability'">
        <section class="dashboard-section"><div class="section-heading compact-heading"><span class="eyebrow">Disponibilidade</span><h2>Horário e indisponibilidades</h2><p>Registe bloqueios pessoais sem alterar a política geral do salão.</p></div><div class="availability-card"><div v-for="day in week" :key="day.name" class="availability-row"><div><strong>{{ day.name }}</strong><small>{{ day.enabled ? `${day.start} — ${day.end}` : 'Indisponível' }}</small></div><label class="switch"><input type="checkbox" v-model="day.enabled"><span></span></label><div class="time-inputs" v-if="day.enabled"><input type="time" v-model="day.start"><span>—</span><input type="time" v-model="day.end"></div></div></div><button class="btn btn-primary" @click="saveAvailability">Guardar disponibilidade</button></section><section class="dashboard-section"><div class="section-heading split compact-heading"><div><h2>Indisponibilidades</h2><p>Bloqueios pontuais de agenda.</p></div><button class="btn btn-outline compact" @click="addBlock">+ Adicionar</button></div><div class="data-list"><div v-for="block in blocks" :key="block.id" class="data-row"><span class="service-icon small">◷</span><div class="data-main"><strong>{{ block.date }}</strong><small>{{ block.time }} · {{ block.reason }}</small></div><button class="text-link danger-text" @click="removeBlock(block)">Remover</button></div></div></section>
      </template>

      <template v-else>
        <section class="dashboard-section"><div class="section-heading compact-heading"><span class="eyebrow">Histórico</span><h2>Atendimentos realizados</h2></div><div class="data-list"><div v-for="i in 6" :key="i" class="data-row"><span class="service-icon small">✓</span><div class="data-main"><strong>{{ ['Corte de cabelo','Barba','Corte infantil'][i%3] }}</strong><small>{{ 14-i }} Set 2026 · Cliente #{{ 2400+i }}</small></div><StatusBadge status="Concluída"/></div></div></section>
      </template>
    </div>
  </main>
</template>
<script>
import { appStore as store, go, showToast } from '../store'
import { professionalAgenda, services } from '../data/mockData'
import StatusBadge from '../components/StatusBadge.vue'
export default { name:'ProfessionalModule',components:{StatusBadge},data:()=>({store,agenda:professionalAgenda.map(x=>({...x})),week:[{name:'Segunda',enabled:true,start:'08:00',end:'17:00'},{name:'Terça',enabled:true,start:'08:00',end:'17:00'},{name:'Quarta',enabled:true,start:'08:00',end:'17:00'},{name:'Quinta',enabled:true,start:'08:00',end:'17:00'},{name:'Sexta',enabled:true,start:'08:00',end:'17:00'},{name:'Sábado',enabled:true,start:'08:00',end:'13:00'},{name:'Domingo',enabled:false,start:'08:00',end:'13:00'}],blocks:[{id:1,date:'18 Set 2026',time:'14:00 — 17:00',reason:'Assunto pessoal'}]}),computed:{title(){return({ 'professional-dashboard':'A sua agenda','professional-services':'Serviços autorizados','professional-availability':'Disponibilidade','professional-history':'Histórico'})[store.view]||'Área profissional'},subtitle(){return({ 'professional-dashboard':'Consulte as marcações e actualize o estado dos atendimentos.','professional-services':'Veja os serviços associados ao seu perfil.','professional-availability':'Ajuste horários e registe indisponibilidades.','professional-history':'Consulte os atendimentos já realizados.'})[store.view]},completed(){return this.agenda.filter(a=>a.status==='Concluída').length},authorizedServices(){return services.filter(s=>[1,2,3,4].includes(s.id))}},methods:{go,checkIn(item){item.status='Em atendimento';showToast('Presença confirmada.')},complete(item){item.status='Concluída';showToast('Atendimento concluído.')},saveAvailability(){showToast('Disponibilidade guardada no mockup.')},addBlock(){this.blocks.push({id:Date.now(),date:'20 Set 2026',time:'10:00 — 12:00',reason:'Indisponibilidade'});showToast('Indisponibilidade adicionada.')},removeBlock(b){this.blocks=this.blocks.filter(x=>x.id!==b.id)}} }
</script>
