<template>
  <main class="page-main" v-if="salon">
    <section class="salon-hero"><div class="shell"><button class="back-link" @click="go('explore')">← Voltar</button><div class="salon-hero-grid"><div class="salon-cover"><span>{{ salon.accent }}</span></div><div class="salon-info"><div class="rating">★ {{ salon.rating }} <span>{{ salon.reviews }} avaliações</span></div><h1>{{ salon.name }}</h1><p>{{ salon.tagline }}</p><div class="salon-info-meta"><span>⌖ {{ salon.area }}, {{ salon.city }}</span><span>◷ {{ salon.hours }}</span><span>{{ salon.open ? '● Aberto agora' : '○ Fechado' }}</span></div><button class="btn btn-primary" @click="startBooking(salon.id)">Marcar serviço</button></div></div></div></section>
    <section class="section shell details-grid"><div class="main-column"><div class="tab-row"><button class="active">Serviços</button><button>Profissionais</button><button>Sobre</button></div><div class="section-heading compact-heading"><h2>Serviços disponíveis</h2><p>Seleccione um serviço para iniciar a marcação.</p></div><div class="service-list"><article v-for="service in salonServices" :key="service.id" class="service-row"><span class="service-icon">{{ service.icon }}</span><div class="service-copy"><strong>{{ service.name }}</strong><small>{{ service.description }}</small><span>{{ service.duration }} min</span></div><div class="service-price"><strong>{{ money(service.price) }}</strong><button class="btn btn-outline compact" @click="startBooking(salon.id, service.id)">Escolher</button></div></article></div></div><aside class="info-card"><h3>Informações</h3><div class="info-line"><span>◷</span><div><strong>Horário</strong><small>{{ salon.hours }}</small></div></div><div class="info-line"><span>⌖</span><div><strong>Localização</strong><small>{{ salon.area }}, {{ salon.city }}</small></div></div><div class="info-line"><span>✓</span><div><strong>Políticas</strong><small>Cancelamento e reagendamento sujeitos às regras do salão.</small></div></div><button class="btn btn-primary full" @click="startBooking(salon.id)">Ver horários</button></aside></section>
  </main>
</template>
<script>
import { appStore as store, go, startBooking, helpers } from '../store'
export default { name:'SalonView', data:()=>({store}), computed:{ salon(){return helpers.salonById(store.selectedSalonId)}, salonServices(){return this.salon.serviceIds.map(helpers.serviceById).filter(Boolean)} }, methods:{go,startBooking,money(v){return `${new Intl.NumberFormat('pt-MZ').format(v)} MT`}} }
</script>
